name: tulip_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  background_location: ^0.11.8
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.1
  dropdown_search: ^5.0.6
  file_picker: ^5.5.0
  firebase_analytics: ^10.7.1
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_messaging: ^14.7.5
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.5
  google_fonts: ^6.1.0
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.1
  flutter_background_service: ^2.4.6
  flutter_background_service_android: ^3.0.3
  package_info_plus: ^4.2.0
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.11
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  flutter_windowmanager: ^0.2.0
  image_picker: ^1.0.2
#  video_player: 2.7.0

dependency_overrides:
  video_player: ^2.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/login_images/
    - assets/dashboard/
    - assets/profile_images/
    - assets/expense_page_icon/
    - assets/menu_icons/
    - assets/other_images/
    - assets/lead_page_icon/
    - assets/lab_images/
    - assets/distributor_images/
    - assets/travel_page_icon/
    - assets/videos/